language: node_js
node_js:
- "node"

sudo: false

cache:
  directories:
  - node_modules

script:
- "npm run build"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  script: "cd docs/.vuepress/dist && echo 'teamlck.com' > CNAME && cd -"
  repo: teamlck/teamlck.github.io
  target-branch: master
  local-dir: docs/.vuepress/dist
  on:
    branch: master
